### ISSUE TITLE
Building nekotatsu from scratch via Termux causes an error when creating the protobuf definitions

### ISSUE THREAD

**Issue by infyProductions** [PhantomShift/nekotatsu#13]
Since I wanted to try to create a version that can run via Termux, I decided to build it from source (note: it's my first time building an app based on rust)

Here's the package list dependencies to install beforehand in order to build successfully:
- rust
- protobuf
- pkg-config
- openssl

As I followed the steps when generating and compiling the protobuf files, I encountered this error (when running `cargo run -p tools generate ./`):
```
thread 'main' panicked at tools/src/main.rs:48:62:
error reading file: Os { code: 21, kind: IsADirectory, message: "Is a directory" }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
Here's some screenshots from two different Termux setups:
1. x86_64 build via Windows Subsystem for Android:
![Screenshot 2024-09-24 133817](https://github.com/user-attachments/assets/3ad35442-8260-4b3c-9398-0a5b519da926)
2. arm64 build via my phone (Realme 6i, android 11):
![Screenshot_2024-09-24-13-32-39-98_84d3000e3f4017145260f7618db1d683](https://github.com/user-attachments/assets/6c5a1fa5-3f96-43a3-8a4a-0db6889e0578)
But I persevered to finish building it and resulted in a working binary in `target/debug` 
![image](https://github.com/user-attachments/assets/f564c310-5868-41cc-9235-bb9ecb398874)
When I was testing, it works as intended and it was successful when importing the recently converted backup file (I have to use MC to copy between the internal storage and the home folder of Termux)
![image](https://github.com/user-attachments/assets/4ca61a10-2b34-419e-bdb8-bc50728cd4ae)

Extra: I have no idea what is this error everytime on my other phone running android 7.1.1
`WARNING: linker: /data/data/com.termux/files/home/nekotatsu/target/debug/tools: unsupported flags DT_FLAGS_1=0x8000001`

**Comment by PhantomShift** [comment]
I haven't tried building on an android system since the nekotatsu cli is intended to be used on the desktop but running it through termux is certainly an interesting solution for keeping the entire conversion process on one device.

As for the error you're facing, `generate ./` does not work since generate takes in a file containing protobuf definitions. However, *when building from scratch from the repository, you do **not** need to generate and compile any protobuf files*; this is specifically for adapting different protobuf definitions that different tachiyomi forks may use; they are largely the same with few exceptions, and with how the protobuf definitions are set up, the omitted fields will work for the most part between backups from different forks.

To reiterate, you do not need to use anything in `tools` unless you are changing the protobuf definitions, which you most likely do not need to do.

**Comment by infyProductions** [comment]
> I haven't tried building on an android system since the nekotatsu cli is intended to be used on the desktop but running it through termux is certainly an interesting solution for keeping the entire conversion process on one device.
> 
> As for the error you're facing, `generate ./` does not work since generate takes in a file containing protobuf definitions. However, _when building from scratch from the repository, you do **not** need to generate and compile any protobuf files_; this is specifically for adapting different protobuf definitions that different tachiyomi forks may use; they are largely the same with few exceptions, and with how the protobuf definitions are set up, the omitted fields will work for the most part between backups from different forks.
> 
> To reiterate, you do not need to use anything in `tools` unless you are changing the protobuf definitions, which you most likely do not need to do.

So... All I needed to do is just run `cargo run` in the cloned repo? That's saves me a lot of time (and battery power for phones/tablets). This might probably the only option for using in android (via termux) since running the precompiled Linux binary and running it on an emulator seems to not work for reasons.

Thanks for the help and clarification
