### ISSUE TITLE
conversion fail again

### ISSUE THREAD

**Issue by flash25ag** [PhantomShift/nekotatsu#8]
as in issue #5 the backup file from mihon / tachiyomi cannot be converted to kotatsu, even though the missing source(apkomik, westmanga, mangacute and etc) is in kotatsu.

here is the error
![Screenshot from 2024-08-02 15-52-47](https://github.com/user-attachments/assets/012e5eb0-e2b4-4a47-b0ba-2890e483675d)

and this is the backup file 
[app.mihon_backup.zip](https://github.com/user-attachments/files/16468266/app.mihon_backup.zip)

**Comment by PhantomShift** [comment]
I have most of these resolved now, and some of them seem to just have changed their top-level domain (i.e. `manhwadesu.one -> manhwadesu.cc`), which I am experimenting with matching, but a significant chunk of the failing conversion (a little over 500 manga) comes from apkomik.

You mentioned that apkomik is in Kotatsu but I wasn't able to find it, do you have a link to where it's implemented or know if it's in Kotatsu under a different name? No promises that I will have an immediate solution if it's under a different name but will be helpful nonetheless.

**Comment by flash25ag** [comment]
Previously, thank you for resolve it.

Actually, the source uses a different name from the domain name, namely komikav.

How about just skipping it for now, if the source is not found, such as adding the command "-s", rather than not being able to convert everything.

**Comment by PhantomShift** [comment]
I see. For now I'll ignore apkomik then. I plan at some point to give users the ability to map sources themselves.

> How about just skipping it for now, if the source is not found, such as adding the command "-s", rather than not being able to convert everything.

This was actually due to two of your sources not being found in the [Keiyoushi](https://github.com/keiyoushi/extensions) repository, but I've now changed the logic to simply warn the user that the extension could not be found instead of completely stopping. I'll update the binaries later today and close this issue when I've done that, thanks for the report!
