### ISSUE TITLE
Kotatsu Parser not found

### ISSUE THREAD

**Issue by abbigailfeil** [PhantomShift/nekotatsu#9]
### Preface

- [X] I have checked that the source is implemented in the [Kotatsu parsers repo](https://github.com/KotatsuApp/kotatsu-parsers)
- [X] I have tried force updating the sources (`nekotatsu update --force-download`)
- [X] (OPTIONAL) The source is listed by [Keiyoushi](https://keiyoushi.github.io/extensions/)
- [x] (OPTIONAL) I have tried converting with soft match on (`--soft-match`)

### Source Name

Comick, Mangakakalot

### Kotatsu Link

https://github.com/KotatsuApp/kotatsu-parsers/blob/master/src/main/kotlin/org/koitharu/kotatsu/parsers/site/mangabox/en/Mangakakalot.kt

### Additional Context

![image](https://github.com/user-attachments/assets/245c5bbc-1b80-4f61-956b-ad1637e133cd)
![image](https://github.com/user-attachments/assets/43a57e6c-3958-4d56-80d1-757a0e1f66d2)

As #8 I'm having a weird situation, I've been using tachi/mihon since 2019 and they had some issues in the past but I always did use my backup anyway I did migrate everything to comick and mangakakalot but it seems comick isn't detected to be converted but I'm pretty sure it's available on kotatsu

except that it seems nekotatsu detect MangaHub (https://mangahub.io), count: 624 but this extension isn't installed, and doesn't show on my mihon, I don't have access to those 624 since 2 years I believe 

Kindly find the attached for my backup, hopefully I can convert to kotatsu family (PS my total manga in my library is 1600)

[eu.kanade.tachiyomi.yokai_2024-08-05_03-22.zip](https://github.com/user-attachments/files/16489400/eu.kanade.tachiyomi.yokai_2024-08-05_03-22.zip)

**Comment by PhantomShift** [comment]
Strange, although I haven't tried importing the backup to Kotatsu yet, I do see that the manga from Comick have converted successfully.

<details>
<summary>Example</summary>

```json
{
  "manga_id": -3148553931699979962,
  "category_id": 2,
  "sort_key": 0,
  "created_at": 0,
  "deleted_at": 0,
  "manga": {
    "id": -3148553931699979962,
    "title": "\"Kukuku……. Yatsu wa Shiten'nou no Naka Demo Saijaku\" to Kaiko sa Reta Ore, Naze ka Yuusha to Seijo no Shishou ni Naru",
    "alt_tile": null,
    "url": "/comic/uiv8RXpC#",
    "public_url": "https://comick.io/comic/uiv8RXpC#",
    "rating": -1.0,
    "nsfw": false,
    "cover_url": "https://meo.comick.pictures/d0WqkQ.jpg#.256.jpg",
    "large_cover_url": "https://meo.comick.pictures/d0WqkQ.jpg#",
    "state": "",
    "author": "",
    "source": "COMICK_FUN",
    "tags": []
  }
}
```
</details>

As for that mangahub source, although you don't have the extension installed, Tachiyomi/Mihon probably kept them in the backup when migrating.

Do I understand correctly that you basically only care about your comick and mangakakalot manga being transferred? In consideration of that, I'll probably implement some sort of whitelist/blacklist functionality for which sources the user wants to transfer from. If you have some additional details about your comick manga not transferring properly I'd appreciate it, otherwise I'll continue investigating with what you've provided so far.

**Comment by abbigailfeil** [comment]
Hello @PhantomShift 
thank you so much for your fast answer Indeed I do care about comick and Mangakakalot

It's very weird since I can see on the cmd log that there are a lot of error coming from comick and mangakakalot,
I've tried migrating all the comick to mangakakalot (to test I know a lot of them didn't migrate correctly) and deleted comick now in the cmd logs it shows error with mangakakalot : [WARNING] Unable to convert 'Brother is not the villain', unknown Tachiyomi/Mihon source (ID: 3470433521851976761)

backup used bellow

[tachi.zip](https://github.com/user-attachments/files/16489679/tachi.zip)

thank you again so much for your amazing support hopefully I can convert and enjoy with you kotatsu

**Comment by abbigailfeil** [comment]
Small Information: Is there a chance that those error are caused by duplication ? cause when I used the imported nekotatsu file to kotatsu I found a lot of duplicate, so maybe mihon do duplicate manhua and they aren't shown in the library of the app and now since i'm converting them maybe nekotatsu is having an issue removing the duplicate ? how can he know which one to keep or which one the most recent one ?

**Comment by PhantomShift** [comment]
Have you actually tried importing it into Kotatsu? You should be able to ignore most of those warnings in the output if you only need comick and mangakakalot, `3470433521851976761` is the ID of some source called 1st Kiss which isn't included in Keiyoushi.

As a general overview,
- `unknown Tachiyomi/Mihon source` means that this extension wasn't found in the extension list (which is Keiyoushi by default)
- `Kotatsu parser not found` means that either Kotatsu hasn't added this source or nekotatsu wasn't able to map it correctly

I don't see anything in the output that indicates that comick or mangakakalot actually failed to convert, and afaik both comick and mangakakalot are included in Keiyoushi and implemented in Kotatsu as you've indicated.

**Comment by abbigailfeil** [comment]
thank you so much meaning that they are from the old 1st kiss hmm interesting 
Then again thank you so so much it's time for me to enjoy the new life of kotatsu that you made it happens

**Comment by PhantomShift** [comment]
Let me know if comick or mangakakalot aren't working properly in the app, otherwise I will close this issue later. Cheers!

**Comment by abbigailfeil** [comment]
everything seems to be working except mangakakalot doesn't work for all the mangas I've imported and I need to find an alternative one by one for every mangakakalot in my library :( 

I was wondering if for a future little project if you can like select your save from kotatsu and have the option to migrate from source X to source Y 

Idk if kotatsu is going to install source migration in the future but for now if a source is dead you need to move it one by one :(

**Comment by PhantomShift** [comment]
Yeah I assume the main problem is the URLs being incorrect. The ID generation procedure on Kotatsu's side is very dependant on the URL, so even if the source is correct, if the URL doesn't match the expected format because the group/site has changed it, it will fail to work in the app.

Source migration is a bit tough because I'd need to incorporate the kotatsu-parsers project to have an actual working solution, but unfortunately I'm not familiar with Java/Kotlin, otherwise I would've worked on this project in those languages and perhaps even get it upstreamed into Kotatsu to simplify the transferring process. 

Sorry to disappoint, but I can't promise a fix for this, though I will be looking into a potential solution.

**Comment by abbigailfeil** [comment]
you've already done too much thank you
